### ISSUE TITLE
make it deployable on heroku

### ISSUE THREAD

**Issue by claimclone** [seldish-og/TikTokBot#1]
hi seldish-og , 
please make it deployable on heroku free dyno for work autopilot & fully free. if we can set hashtag for scrape from instagram to heroku env vars it's so much usefulness. also heroku have wide range of buildpacks like selenium , chrome headless & using set workers in Procfile , u can autorun important cmds after awake dyno from sleep.
waiting for your changes commits :)
finest regards
goodbye

**Comment by seldish-og** [comment]
Thanks for reply! I'll do my best to realize this function. I had experience  with heroku.

**Comment by seldish-og** [comment]
You can change 126 line and put any hashtag you need instead of "funnyvideos"

**Comment by claimclone** [comment]
hello again seldish-og , 
at the first thanks for your response ,
please make changes to work with heroku buildpacks , it's now read from windows path like line 18 tik_tok.py :
self.browser = webdriver.Chrome("chromedriver.exe")
must be change for work with chrome headless builpack.
waiting for your changes commits :)
finest regards
goodbye
