### ISSUE TITLE
make changes for work with herkku builpacks

### ISSUE THREAD

**Issue by claimclone** [seldish-og/TikTokBot#2]
hello again seldish-og ,
at the first thanks for your response ,
please make changes to work with heroku buildpacks , it's now read from windows path like line 18 tik_tok.py :
self.browser = webdriver.Chrome("chromedriver.exe")
must be change for work with chrome headless builpack.
waiting for your changes commits :)
finest regards
goodbye

**Comment by seldish-og** [comment]
Ok, I'll make it. Star project if you are interested in, thanks

**Comment by claimclone** [comment]
hello again seldish-og,
please don't forget heroku changes must doing to compatible to deployable on heroku.
waiting for your changes commits
finest regards

**Comment by seldish-og** [comment]
.
