### ISSUE TITLE
Captcha doesn't solved.

### ISSUE THREAD

**Issue by traffhub** [seldish-og/TikTokBot#4]
U cant slide slider for some coords, cause it evething move by a half of slidebar. 

https://user-images.githubusercontent.com/66271425/133346482-86e9d5cd-bb8d-4338-a657-6d5dfc6fc658.mp4

**Comment by seldish-og** [comment]
Idk, it works for me. Tik-tok changed website, so you need to find the puzzle cords first, and then move-and-hold 3 or 2 times to this puzzle. I mean you should imitate users behaviour, user hand.

**Comment by traffhub** [comment]
> Idk, it works for me. Tik-tok changed website, so you need to find the puzzle cords first, and then move-and-hold 3 or 2 times to this puzzle. I mean you should imitate users behaviour, user hand. Sent from Mail.ru app for iOS Wednesday, 15 September 2021, 02:23 +0300 from ***@***.*** ***@***.***>:
> […](#)
> U cant slide slider for some coords, cause it evething move by a half of slidebar. https://user-images.githubusercontent.com/66271425/133346482-86e9d5cd-bb8d-4338-a657-6d5dfc6fc658.mp4 — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub , or unsubscribe .

Yes, I figured out how to move the slider. But I can't understand why cv2 keeps giving out different coordinates? 
That is, adding a measurement uncertainty does not give any result. Can you help with this please?

**Comment by seldish-og** [comment]
When you open web page, you can see that captcha appears, my code download captcha and captcha key(the puzzle which you move).
Then this 2 pictures transmitted to cv2 function. There cv2 analysis main captcha picture and find coordinates to cut part. And then return this number.

It returns different coordinates, because captchas are different. They have different distance to cut part.

**Comment by traffhub** [comment]
> When you open web page, you can see that captcha appears, my code download captcha and captcha key(the puzzle which you move). Then this 2 pictures transmitted to cv2 function. There cv2 analysis main captcha picture and find coordinates to cut part. And then return this number. It returns different coordinates, because captchas are different. They have different distance to cut part.

I got u, I have test exectly the same code. But i Have that trouble with "return this number" in cv2. It does not return the correct coordinates of cut part. At first I thought it was a matter of measurement error.  But the slider moves the cut out part to the right and to the left of the desired.  Sometimes it solves the captcha, but that's random.

Example: 

https://user-images.githubusercontent.com/66271425/133452197-dc3dc072-b49e-4efd-b402-b953fc4391fd.mp4



PS> R u Russian by any chance?

**Comment by traffhub** [comment]
I think trouble with 
         captcha = cv2.imread(captcha_background_path, 0)
            key = cv2.imread(key_path, 0)
            method = eval('cv2.TM_CCOEFF')
            match = cv2.matchTemplate(captcha, key, method)
            min_val, max_val, min_loc, max_loc = cv2.minMaxLoc(match)
            print('key coords: ',int(max_loc[0]) + 24)
            return int(max_loc[0]) + 24


Its not currectly find coords, I think.

**Comment by seldish-og** [comment]
Got you. This is because of comparing images method. You can try other methods they could work better. Also cv2 isn’t an ideal library, so not all captchas will be solved


When you open web page, you can see that captcha appears, my code download captcha and captcha key(the puzzle which you move). Then this 2 pictures transmitted to cv2 function. There cv2 analysis main captcha picture and find coordinates to cut part. And then return this number. It returns different coordinates, because captchas are different. They have different distance to cut part.

**Comment by traffhub** [comment]
More examples: 

https://user-images.githubusercontent.com/66271425/133454185-ba8e458e-7974-4c3f-9793-c5b3e20f84a0.mp4

**Comment by traffhub** [comment]
> Got you. This is because of comparing images method. You can try other methods they could work better. Also cv2 isn’t an ideal library, so not all captchas will be solved When you open web page, you can see that captcha appears, my code download captcha and captcha key(the puzzle which you move). Then this 2 pictures transmitted to cv2 function. There cv2 analysis main captcha picture and find coordinates to cut part. And then return this number. It returns different coordinates, because captchas are different. They have different distance to cut part.
> […](#)
> I got u, I have test exectly the same code. But i Have that trouble with "return this number" in cv2. It does not return the correct coordinates of cut part. At first I thought it was a matter of measurement error. But the slider moves the cut out part to the right and to the left of the desired. Sometimes it solves the captcha, but that's random. Example: https://user-images.githubusercontent.com/66271425/133452197-dc3dc072-b49e-4efd-b402-b953fc4391fd.mp4 PS> R u Russian by any chance? — You are receiving this because you commented. Reply to this email directly, view it on GitHub , or unsubscribe .

Thank u for your reply!

**Comment by seldish-og** [comment]
Thanks for the attention to my project! Lately I’ll upload more recent version of this file, it works better
