### ISSUE TITLE
error

### ISSUE THREAD

**Issue by gioimtg2003** [seldish-og/TikTokBot#5]
hello seldish-og,
when i run the program there is an error :
File "c:\Phá captcha\tik_tok.py", line 160, in <module>
    tik_tok_parser = TikTokBot()
  File "c:\Phá captcha\tik_tok.py", line 19, in __init__
    with open("config.json", "r") as file_config:
FileNotFoundError: [Errno 2] No such file or directory: 'config.json'
and i am a beginner so please help me,
I appreciate your feedback, thanks

**Comment by seldish-og** [comment]
Hello!
Thank you for your feedback)
You need to create new file(config.json), where you should write your email and password in json format.
Also If you need some more help with this project you can write me in telegram (you can see link in my GitHub bio)


hello seldish-og,

**Comment by gioimtg2003** [comment]
> 

thanks for your help
